"""Add last_remind_time to Task model

Revision ID: 36a29fb30b73
Revises: 57b76386679f
Create Date: 2024-10-11 02:39:21.644124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a29fb30b73'
down_revision = '57b76386679f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_remind_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('last_remind_time')

    # ### end Alembic commands ###
