"""Add completed_at to Task

Revision ID: 57b76386679f
Revises: 7669198cdba0
Create Date: 2024-10-11 00:28:30.475330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b76386679f'
down_revision = '7669198cdba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('reminder_sent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_sent', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
